version: '3'
services:

#nginx-1
  nginx-1:
    container_name: nginx-1
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx_log/nginx-1:/var/log/nginx:cache
      - ./nginx/conf/defaut.conf:/etc/nginx/conf.d/default.conf:cache

#nginx-2
  nginx-2:
    container_name: nginx-2
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./nginx/nginx_log/nginx-2:/var/log/nginx:cache
      - ./nginx/conf/defaut.conf:/etc/nginx/conf.d/default.conf:cache

#nginx-3
  nginx-3:
    container_name: nginx-3
    image: nginx:latest
    ports:
      - 82:80
    volumes:
      - ./nginx/nginx_log/nginx-3:/var/log/nginx:cache
      - ./nginx/conf/defaut.conf:/etc/nginx/conf.d/default.conf:cache

#telegraf
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    volumes:
      - ./nginx/nginx_log/nginx-1:/var/log/nginx-1:cache
      - ./nginx/nginx_log/nginx-2:/var/log/nginx-2:cache
      - ./nginx/nginx_log/nginx-3:/var/log/nginx-3:cache
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - ./log.out:/tmp/log.out
    depends_on:
      - nginx-1
      - timescaledb

#timescaledb
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=timescale
      - POSTGRES_DB=timescaledb
    ports:
      - 5432:5432
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data:cache

#grafana
  grafana:
      container_name: grafana
      image: grafana/grafana:latest
      ports:
        - 3000:3000
      volumes:
        - ./grafana/grafana_data:/var/lib/grafana
      depends_on:
        - timescaledb